### ISSUE TITLE
Steinhardt’s parameters change upon creating supercell

### ISSUE THREAD

**Issue by dgehringer** [pyscal/pyscal#104]
Dear `pyscal` team!

I wanted to use `pyscal` to calculate Steinhardt’s parameters. Before doing so I did some sanity checks. 

**The bug**
Steinhardt’s parameters change when creating supercells. Actually I could not figure out if periodic boundary conditions are applied. In case not I guess this is intended behaviour!

**To Reproduce**
  1. I have created a simple *fcc*-Al bulk structure
  ```python
  fcc_al = ase.build.bulk("Al", crystalstructure="fcc", a=4.05)
  ```
  2. To convert from `ase.Atoms` to `pyscal.core.System`, I use the following function
  ```python
  def to_pyscal_structure(structure: ase.Atoms) -> pyscal.core.System:
    system = pyscal.core.System()
    system.box = structure.get_cell().tolist()
    system.atoms =  \
        [
            pyscal.core.Atom(id=i,pos=pos) 
            for i, pos 
            in enumerate(structure.get_scaled_positions())
        ]
    return system
  ```
  3.  To finally obtain the *q* parameters
  ```python
def get_q(structure: ase.Atoms, q_orders=range(2,13)) -> dict:
    system = to_pyscal_structure(structure)
    system.find_neighbors(method="voronoi")
    system.calculate_q(q_orders)
    q = system.get_qvals(q_orders)
    return {qi: qq for qi, qq in zip(q_orders, q)}
  ```

**Expected behavior**
By creating a supercell the local environment does not change, consequently one would expect Steinhardt's parameters to remain constant.

**Figure**

Plotting *q2* to *q12* with the following code:
```python
fcc_al = ase.build.bulk("Al", crystalstructure="fcc", a=4.05)
colors = "-rgbk"
for i in reversed(range(1,5)):
    plt.plot(*f(get_q)(fcc_al*(i,i,i)), color=colors[i])
    plt.plot([],[], label=rf"${i}\times{i}\times{i}$",color=colors[i])
plt.legend()
plt.show()
```

yields

![supercell](https://user-images.githubusercontent.com/35268573/124586066-4ae4e280-de56-11eb-9d5a-7facdd33d581.png)

The graph clearly shows that although `pyscal` calculates the same *q* parameters for each site, which is as one would expect it, for a certain supercell dimension. However, changing those dimensions varies the *q*-parameters, which is unexpected since the atomic environment stays the same.

**P. S.:** Changing the `method` keyword arg to `cutoff` or `sann` does not cure this behaviour ;=)

Do you see something wrong in my approach? I kindly ask you for your insight

**Comment by srmnitc** [comment]
@dgehringer Thanks for the detailed bug report with the examples. I checked the code that you provided. This error is caused by the following line in the `to_pyscal_structure` method:
```
structure.get_scaled_positions()
```
pyscal takes the cartesian coordinates as input, not the direct ones. Using `structure.positions` instead will work. However, I would like to point out the pyscal inbuilt method for ase atom objects:
```
system = pyscal.core.System()
system.read_inputfile(structure, format="ase")
```
where `structure` is an ASE object. This will work directly and do the conversion to pyscal structure objects within. Thanks for trying pyscal, and for reaching out! If the issue is resolved with the above changes, feel free to close it.

**Comment by dgehringer** [comment]
Many thanks for your response!
Indeed it works as intended!

Just a final small annotation:
I've inferred to use of fractional coordinates, from your [documentation](https://pyscal.org/part1/01_getting_started.html#the-atom-class) of the `Atom` class, especially from this snippet here:
```python
atom1 = pc.Atom(pos=[0., 0., 0.], id=0)
atom2 = pc.Atom(pos=[0.5, 0.5, 0.5], id=1)
```
which looks like fractional coords at a first glance.

**Comment by srmnitc** [comment]
@dgehringer Yes, I see how that can be misleading. I will fix the documentation. Thanks for the feedback. I have raised an [issue](https://github.com/srmnitc/pyscal/issues/105) and will fix it in the next release!
