### ISSUE TITLE
Periodic Boundary Conditions

### ISSUE THREAD

**Issue by lydiash** [pyscal/pyscal#106]
Is there a way to take into account periodic boundary conditions when creating a system? I am having trouble getting Voronoi volumes to be calculated correctly because it is not taking into account the periodic boundary conditions.

**Comment by lydiash** [comment]
It seems that this is the snippet of code that will fix my particular problem, since I have already created ase atoms objects with pbc : 
```
system = pyscal.core.System()
system.read_inputfile(structure, format="ase")
```
However, I found this by examining a closed issue in the code, not in the documentation. Maybe I just missed it in the docs.

**Comment by srmnitc** [comment]
Thanks for the feedback, will update the docs.
