### ISSUE TITLE
Installation Problems  on ubuntu 20.04

### ISSUE THREAD

**Issue by NoelJakse** [pyscal/pyscal#112]
**Describe the bug**
Hello everyone,

successful installation of pyscal 2.10.14 on ubuntu 20.04 using as shown below:

![image](https://user-images.githubusercontent.com/77833371/137619131-2814f441-c4bd-440d-b686-8abbda8bafd3.png)

Trying the simple test proposed on the website:

![image](https://user-images.githubusercontent.com/77833371/137619325-88786423-6a81-423b-8844-9f05e013a22c.png)

It fails. Sooo trying the getting started example on the website:

![image](https://user-images.githubusercontent.com/77833371/137619627-bae8c932-b9d9-4de8-897f-f2d9048d564d.png)

But things are not going better. 

It seems that something went wrong but can't identifying it 

I'll be grateful for any help

Best
Noel

**Comment by srmnitc** [comment]
Hi @NoelJakse, thanks for reporting this issue. Although I am not sure whether it is the problem, the installation instructions in the documentation was outdated. Could you please uninstall existing versions and try:

```
pip install pybind11
pip install git+https://github.com/pyscal/pyscal
```

If this does not work, cloning the repository and installing should be better:

```
git clone https://github.com/pyscal/pyscal.git
pip install pybind11
cd pyscal
python setup.py install
```

If it is a system wide installation, maybe `--user` needs to be added to the last step. I checked both on a Ubuntu 20.04 machine and it seems to work for me. Please let me know if you still have this issue!

The updated pyscal version should be 2.10.15.

**Comment by NoelJakse** [comment]
Many thanks @srmnitc !

It seems to work now directly with the first method
 
![image](https://user-images.githubusercontent.com/77833371/137633359-b38bcde2-32f2-47de-9e75-d1603db397cf.png)

And thanks for this brand new version 2.10.15

Best
Noel

**Comment by srmnitc** [comment]
Great, thanks! I will close this issue now.
