### ISSUE TITLE
NumPy and matplotlib should added as requirements

### ISSUE THREAD

**Issue by bocklund** [pyscal/pyscal#31]
I'm working on my JOSS review for this project (at https://github.com/openjournals/joss-reviews/issues/1824)

I installed `pyscal` into an Anaconda environment on macOS, but NumPy and matplotlib were not installed into that environment and I had to install them manually. I think this is caused because NumPy is only a `build` requirement, not a `run` requirement in `conda-recipe/meta.yaml`. When `pyscal` is installed via `conda`, neither NumPy nor matplotlib are installed.

This can be checked by running `conda search -c pyscal pyscal --info`, which only shows Python as a dependency.

**Comment by srmnitc** [comment]
Thanks for the feedback. I will fix this issue soon and get back to you.

**Comment by srmnitc** [comment]
c81fb029e684b7a4cb5e964203cc42386c1f9216 should fix this issue. Both numpy and matplotlib has been added as dependencies.
