### ISSUE TITLE
Links in documentation

### ISSUE THREAD

**Issue by lucydot** [pyscal/pyscal#34]
Part of JOSS review process at openjournals/joss-reviews#1824 .
I think the documentation is great! Just a few minor points.

I worked through the notebooks on binder and spotted a couple of points where linking to further information might be useful.

- A link to Jupyter Notebook documentation would be useful for users who are not familiar with notebooks.

- In the solid/liquid example notebook a link to https://pyscal.readthedocs.io/en/latest/solidliquid.html would be useful.

**Comment by lucydot** [comment]
Another link and clarification that could be added to the basic example notebook would be that values should not be assigned to `sys.atoms[0]` , as highlighted elsewhere in the documentation ([link](https://pyscal.readthedocs.io/en/latest/example1basic.html#combining-system-and-atom)). The notebook example seems to suggest you can use it for getting values (`atom = sys.atoms[0]`), which is contradicted in the previous link.

**Comment by srmnitc** [comment]
Thanks for the suggestions! I have implemented the recommendations in commit d577ccbaa6e3baa47836e7135989e6702ac8c580. I am closing this issue now.
