### ISSUE TITLE
How to load ASE structures? 

### ISSUE THREAD

**Issue by jan-janssen** [pyscal/pyscal#36]
Currently I use: 

```
sys = pc.System()
sys.box = [[0.0, structure.cell[0][0]], [0.0, structure.cell[1][1]], [0.0, structure.cell[2][2]]]
sys.atoms = [pc.Atom(pos=p.tolist(), id=i) for i, p in enumerate(structure.positions)]
```

Is there a more efficient way?

**Comment by srmnitc** [comment]
As of now, there is no better way. An interface for ase structures can be implemented. I will keep this issue open, and implement a better way.

**Comment by jan-janssen** [comment]
In particular for non-cubic cells it might be helpful to take a look at https://gitlab.com/ase/ase/blob/master/ase/calculators/lammps/coordinatetransform.py

**Comment by srmnitc** [comment]
Commit 0bdf7523c1d1242e1c3d82a382e4821eb57d2d9e gives an 'ase' options for reading in input. For example the [ase Atoms](https://wiki.fysik.dtu.dk/ase/ase/atom.html#module-ase.atom) can be directly provided as input.
```
aseobj = ase.io.read(filename)
sys = pyscal.core.System()
sys.read_inputfile(aseobj, format='ase')
```
would read from the ase Atoms object. Triclinic boxes can also be read in by providing the `is_triclinic` keyword as True for `read_inputfile`.
