### ISSUE TITLE
Link pyscal from the pyiron website

### ISSUE THREAD

**Issue by jan-janssen** [pyscal/pyscal#64]
@srmnitc we are currently in process of redesigning the pyiron website. As part of this we want to link to all the projects we integrated https://pyiron.org/collaborators/ . Is it ok if we use the pyscal logo for such a backlink to pyscal?

**Comment by srmnitc** [comment]
Sure that would be great!

**Comment by jan-janssen** [comment]
I opened a pull request to add it - it should be there within the next few days https://github.com/pyiron/pyiron.github.io/pull/24
