### ISSUE TITLE
Adaptive Common Neighbour Analysis

### ISSUE THREAD

**Issue by jan-janssen** [pyscal/pyscal#74]
I tried to update our interface method to use pyscal rather than ovito and noticed the results for the same structure differ. An example structure is available in:
https://github.com/jan-janssen/ovito-vs-pyscal
and the comparison can be accessed via mybinder: 
https://mybinder.org/v2/gh/jan-janssen/ovito-vs-pyscal/master?filepath=ovito-vs-pyscal.ipynb

I wrote a short wrapper around the pyscal code to return the output in the ovito format and these are the results of the comparison: 

Ovito:
```
{'CommonNeighborAnalysis.counts.BCC': 10, 'CommonNeighborAnalysis.counts.FCC': 5387, 'CommonNeighborAnalysis.counts.HCP': 0, 'CommonNeighborAnalysis.counts.ICO': 0, 'CommonNeighborAnalysis.counts.OTHER': 2603}
```

pyscal:
```
{'CommonNeighborAnalysis.counts.OTHER': 3701,
 'CommonNeighborAnalysis.counts.FCC': 4296,
 'CommonNeighborAnalysis.counts.HCP': 0,
 'CommonNeighborAnalysis.counts.BCC': 3,
 'CommonNeighborAnalysis.counts.ICO': 0}
```

For the interface method it is important to identify the regions of solid structure, so in this case primarily FCC vs. OTHER.

**Comment by srmnitc** [comment]
Thanks for pointing it out @jan-janssen ! I will check the issue.

**Comment by jan-janssen** [comment]
Still the results for the melting point calculation give more or less similar results (926K): 
https://github.com/jan-janssen/melting-pyscal/blob/master/plot.ipynb
and (927K): 
https://github.com/pyiron/pyiron_meltingpoint/blob/master/examples/fccAl/plot.nbconvert.ipynb

**Comment by srmnitc** [comment]
Thanks! Thats good to know. So far I have been unable to see why this difference occurs.

**Comment by jan-janssen** [comment]
I noticed an other issue:
```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-5-2b18f17b0857> in <module>
----> 1 analyse_cna_adaptive(struct, mode="total")

<ipython-input-2-ed0435d41a51> in analyse_cna_adaptive(atoms, mode)
     20     sys = pc.System()
     21     sys.read_inputfile(atoms, format="ase")
---> 22     cna = sys.calculate_cna(cutoff=None)
     23 
     24     if mode == "total":

/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/site-packages/pyscal/core.py in calculate_cna(self, cutoff, calculate_neighbors)
   1267         if cutoff is None:
   1268             if calculate_neighbors:
-> 1269                 self.find_neighbors(method="number", nmax=14, assign_neighbor=False)
   1270             cna = self.calculate_acna()
   1271             return cna

/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/site-packages/pyscal/core.py in find_neighbors(self, method, cutoff, threshold, filter, voroexp, padding, nlimit, cells, nmax, assign_neighbor)
    558             finished = self.get_all_neighbors_bynumber(threshold, nmax, assign_neighbor)
    559             if not finished:
--> 560                 raise RuntimeError("Could not find enough neighbors - try increasing threshold")
    561 
    562         elif method == 'voronoi':

RuntimeError: Could not find enough neighbors - try increasing threshold
```

I uploaded the `POSCAR` file to the repository above https://github.com/jan-janssen/ovito-vs-pyscal/blob/master/POSCAR2

**Comment by srmnitc** [comment]
This one is easier! It is one of the configurations with 'holes'. Pyscal is just complaining that there are not enough 'reasonable' neighbors for some atoms, which is quite true. This can be overcome by raising the threshold values. I will do it.

**Comment by jan-janssen** [comment]
That would be great, it is really just a single calculation where the calculation failed, so I am quite optimistic that we can use pyscal, we just have to figure out what causes the difference in counts then I am happy to update the official version.

**Comment by srmnitc** [comment]
Yeah, I am taking a look at the difference in counts again tomorrow. Hopefully, this will be sorted out soon.

**Comment by srmnitc** [comment]
> I noticed an other issue:
> 
> ```
> ---------------------------------------------------------------------------
> RuntimeError                              Traceback (most recent call last)
> <ipython-input-5-2b18f17b0857> in <module>
> ----> 1 analyse_cna_adaptive(struct, mode="total")
> 
> <ipython-input-2-ed0435d41a51> in analyse_cna_adaptive(atoms, mode)
>      20     sys = pc.System()
>      21     sys.read_inputfile(atoms, format="ase")
> ---> 22     cna = sys.calculate_cna(cutoff=None)
>      23 
>      24     if mode == "total":
> 
> /u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/site-packages/pyscal/core.py in calculate_cna(self, cutoff, calculate_neighbors)
>    1267         if cutoff is None:
>    1268             if calculate_neighbors:
> -> 1269                 self.find_neighbors(method="number", nmax=14, assign_neighbor=False)
>    1270             cna = self.calculate_acna()
>    1271             return cna
> 
> /u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.7/site-packages/pyscal/core.py in find_neighbors(self, method, cutoff, threshold, filter, voroexp, padding, nlimit, cells, nmax, assign_neighbor)
>     558             finished = self.get_all_neighbors_bynumber(threshold, nmax, assign_neighbor)
>     559             if not finished:
> --> 560                 raise RuntimeError("Could not find enough neighbors - try increasing threshold")
>     561 
>     562         elif method == 'voronoi':
> 
> RuntimeError: Could not find enough neighbors - try increasing threshold
> ```
> 
> I uploaded the `POSCAR` file to the repository above https://github.com/jan-janssen/ovito-vs-pyscal/blob/master/POSCAR2

This is now fixed

**Comment by srmnitc** [comment]
pyscal cna results are now slightly better:
```
{'other': 3011, 'fcc': 4984, 'hcp': 0, 'bcc': 5, 'ico': 0}
```

**Comment by srmnitc** [comment]
New results-
```
{'others': 2606, 'fcc': 5384, 'hcp': 0, 'bcc': 10, 'ico': 0}
```
