### ISSUE TITLE
Detector for Diamond structures 

### ISSUE THREAD

**Issue by jan-janssen** [pyscal/pyscal#75]
**Is your feature request related to a problem? Please describe.**
We want to calculate melting points for Silicon so we need a detector for diamond structures. 

**Describe the solution you'd like**
The detector is described in the following paper: https://arxiv.org/abs/1601.06597

**Describe alternatives you've considered**
Currently we use a Ovito based implementation, the Ovito diamond analysis is documented here:
https://www.ovito.org/docs/current/particles.modifiers.identify_diamond_structure.php
And an example for the melting point calculation with diamond structures is available on GitHub:
https://github.com/jan-janssen/melting-diamonds

**Additional context**
It is mainly an optional feature and maybe an implementation based on the steinhart parameters already solves the issue, still it would be an interesting feature to add.

**Comment by srmnitc** [comment]
From an experience in diamond systems, q6 parameter automatically solves the issue. Nevertheless this is indeed an interesting one. Its partly available at the moment - https://github.com/srmnitc/pyscal/blob/master/src/pyscal/core.py#L567 . I will update the method too.

**Comment by srmnitc** [comment]
This is now implemented. In the new version, the method can be called using `identify_diamond` method.
