### ISSUE TITLE
How is the voronoi volume calculated? 

### ISSUE THREAD

**Issue by jan-janssen** [pyscal/pyscal#84]
**Describe the bug**
The voronoi volume disagrees with the one calculated from ovito 

**To Reproduce**
https://github.com/jan-janssen/ovito-vs-pyscal/blob/master/ovito-vs-pyscal-small.ipynb

**Expected behavior**
Both results should be the same.

**Comment by srmnitc** [comment]
Thanks for the report. This is problem with non-cubic boxes. Passing a structure with `cubic=True` seems to give the exact volume. The reason is that the current Voro++ interface is only for cubic boxes. I will have to check a bit on how this can be fixed.

**Comment by srmnitc** [comment]
Just not fixed due to time constraints unfortunately. Will get back to this as soon as possible! Hopefully in the next few days.

**Comment by srmnitc** [comment]
@jan-janssen The [new release](https://github.com/srmnitc/pyscal/releases/tag/2.10.3) should fix this problem.
