### ISSUE TITLE
Per atom diamond structure information 

### ISSUE THREAD

**Issue by jan-janssen** [pyscal/pyscal#85]
**Is your feature request related to a problem? Please describe.**
Currently I use: 
```
sys = pc.System()
sys.read_inputfile(si_dia, format="ase")
print(sys.identify_diamond())
```
This gives me: 
```
{'others': 0,
 'fcc': 0,
 'hcp': 0,
 'bcc': 0,
 'ico': 0,
 'cubic diamond': 2,
 'cubic diamond 1NN': 0,
 'cubic diamond 2NN': 0,
 'hex diamond': 0,
 'hex diamond 1NN': 0,
 'hex diamond 2NN': 0}
```

**Describe the solution you'd like**
I would like to know the type of the individual atoms.

**Comment by srmnitc** [comment]
You can do this by- 
```
atoms = sys.atoms
atoms[0].structure
```
That returns an integer. The meaning of integer is explained [here](https://docs.pyscal.org/en/latest/pyscal.html#pyscal.core.System.identify_diamond)

**Comment by jan-janssen** [comment]
Thanks
