### ISSUE TITLE
Centrosymmetry for a diamond structure 

### ISSUE THREAD

**Issue by jan-janssen** [pyscal/pyscal#87]
**Describe the bug**
I have the feeling periodic boundaries are not correctly included when calculating centro symmetry for diamond structure 

**To Reproduce**
https://github.com/jan-janssen/ovito-vs-pyscal/blob/master/ovito-vs-pyscal-centro-diamond.ipynb

**Additional context**
Related pyiron issue https://github.com/pyiron/pyiron/pull/1202

**Comment by srmnitc** [comment]
Fixed in 3177ea54add2b3ac4c58cfede9ad7630ac4d788b

**Comment by jan-janssen** [comment]
I just checked the example above and the results are still different. 
ovito: 
```
[16.585255, 22.11367 , 22.11367 , 22.113663, 22.11367 , 22.113663, 22.11367 , 22.113663]
```
pyscal: 
```
[22.113675, 16.58525625, 16.58525625, 16.58525625, 16.58525625, 22.113675, 22.113675, 22.113675]
```

**Comment by srmnitc** [comment]
This is not a bug actually. The centrosymmetry measures the inverse symmetry. For a diamond structure, the first shell has 4 atoms. If you include the second shell, then that would be 16 atoms in total. For both 4 and 16 as number of neighbors, pyscal, ovito and LAMMPS gives the same centrosymmetry value. For any number of neighbors between 4-16, the value will depend on which neighbors are selected. It should be 16.58 or 22.11 for each atom, but the number of atoms with these would depend on which neighbors are selected from the second shell. As such, pyscal, ovito and LAMMPS all differs in the number of atoms with 16.58 and 22.11. I think as such it is not a bug, in my opinion for the test cases, either 4/16 should be selected for diamond, 6/14 for bcc and 12 for both fcc and hcp.

**Comment by jan-janssen** [comment]
@srmnitc thx for the explanation
