### ISSUE TITLE
Diamond detector crashes for relaxed structure

### ISSUE THREAD

**Issue by jan-janssen** [pyscal/pyscal#90]
If the cell is larger than 4000 atoms the kernel crashes when applying the diamond analysis on a relaxed structure for a cell smaller than 4000 atoms it works. If the cell is not relaxed it works as well. 
https://github.com/jan-janssen/wired-pyscal-bug

**Comment by srmnitc** [comment]
@jan-janssen I wanted to extract the final structure for some testing. Can I access the final structure(the one that crashes) by
```
job.get_final_structure()
```

**Comment by srmnitc** [comment]
Sorry I saw how to do this :)

**Comment by srmnitc** [comment]
The problem is with the cell list in pyscal. In this particular case, there is an atom which lies exactly on the box edge. This was a condition which the cell list algo missed. I will update soon.

**Comment by srmnitc** [comment]
Should be fixed in the new release https://github.com/srmnitc/pyscal/releases/tag/2.10.5

**Comment by jan-janssen** [comment]
Thanks a lot - I give it a try once the conda package is available.

**Comment by jan-janssen** [comment]
Perfect the test notebook works now, so I am going to give the melting point calculation another try.
