### ISSUE TITLE
Installation via pip 

### ISSUE THREAD

**Issue by jan-janssen** [pyscal/pyscal#92]
When naively installing pyscal via pip: 
```
pip install pyscal
```
I got a different package https://pypi.org/project/pyscal/ which corresponds to https://github.com/equinor/pyscal so I do not think there is any chance they are going to hand over this name any time soon. The funny part is they started publishing their package on pip on the 1st of October 2019 and you started publishing on conda on the 24th of October 2019. Anyway over the mid-term I guess it would be great to have consistent naming for both the pip and the conda version even if this means renaming the package.

**Comment by srmnitc** [comment]
yeah this is extremely unfortunate. I actually tried to upload on pypi on the second of October and realized to my surprise that it was gone! What do you recommend? I could envision renaming the package, if we get to keep the imports same. For example, the packages could be called `pyscal-core`, but we still could do `import pyscal.core as pc`. Would it be possible then to also maintain pyscal name in conda-forge. I really do not know how to go forward with this.

**Comment by jan-janssen** [comment]
Hi @srmnitc sorry for the delay, I really like the idea of having a package named `pyscal-core` and then in the `pyscal` conda package you would simply have `pyscal-core` as the only dependency, so that should be fine.

**Comment by srmnitc** [comment]
I am in agreement with idea! I am would love some help from your side though. The first time I tried I was not so successful in getting the compiled C++ side of the code through pip.

**Comment by jan-janssen** [comment]
> I am in agreement with idea! I am would love some help from your side though. The first time I tried I was not so successful in getting the compiled C++ side of the code through pip.

Sure, but I guess now that `pyscal` is build within conda it should basically be the same command right?

**Comment by srmnitc** [comment]
pyscal can now be installed by `pip install pyscal2`
