### ISSUE TITLE
Voronoi Analysis works fine for 128 atoms but fails for 250 atoms and larger 

### ISSUE THREAD

**Issue by jan-janssen** [pyscal/pyscal#93]
**Describe the bug**
I calculate:
```
np.mean(lst), np.max(lst), np.min(lst), np.std(lst)
(17.652945, 17.65295, 17.652939, 2.5246266e-06)  # small cell 
(26.47941835024731, 70.12143498554614, 17.3288579518855, 14.405461275280086)   # large cell 
```

**To Reproduce**
https://github.com/jan-janssen/ovito-vs-pyscal/blob/master/ovito-vs-pyscal-voronoi.ipynb

**Expected behavior**
The mean, maximum, minimum and standard deviation should not change when changing the simulation cell 

**Additional context**
The melting point calculations seem to be all fine for fcc, bcc and diamond structures just hcp fails: 
https://github.com/jan-janssen/pyiron_meltingpoint

**Comment by srmnitc** [comment]
Thanks for pointing this out. Now fixed. I will make a release soon.

**Comment by jan-janssen** [comment]
I can confirm it is fixed with the new release. I now opened a pull request for migrating the melting point protocol to pyscal and the results look very promising https://github.com/pyiron/pyiron_meltingpoint/pull/9#issuecomment-738643029 - maybe you can even use it to compare your melting points.
