### ISSUE TITLE
Voronoi Analysis crashes for large structures

### ISSUE THREAD

**Issue by jan-janssen** [pyscal/pyscal#95]
I currently run melting point calculation with pyscal 2.10.6 and the voronoi analysis crash the jupyter kernel, so some structures, while others work fine.

**Comment by jan-janssen** [comment]
It seems the cache is not cleared after the calculation of the voronoi volume, so after multiple large structures the kernel crashes.

**Comment by jan-janssen** [comment]
I uploaded an example here https://github.com/jan-janssen/pyscal_voronoi_crash

**Comment by srmnitc** [comment]
Thanks! I will look into it now

**Comment by srmnitc** [comment]
Fixed! Will create a release soon.

**Comment by jan-janssen** [comment]
Thanks - the issue is now fixed.
