### ISSUE TITLE
pyscal calls itself when analyzing lammps trajectory?

### ISSUE THREAD

**Issue by tanooj-s** [pyscal/pyscal#98]
Hi, I've been trying to run the tutorial to [analyze a lammps trajectory](https://pyscal.org/part3/03_01_steinhardts_parameters_for_lammps.html) but I get an error when running the line `q6s = [calculate_q6(traj[x]) for x in range(traj.nblocks)]`. 

The error output is

```
NameError                                 Traceback (most recent call last)
<ipython-input-6-94b1f50c34f9> in <module>
----> 1 q6s = [calculate_q6(traj[x]) for x in range(traj.nblocks)]

<ipython-input-6-94b1f50c34f9> in <listcomp>(.0)
----> 1 q6s = [calculate_q6(traj[x]) for x in range(traj.nblocks)]

<ipython-input-5-5ab23f542214> in calculate_q6(timeslice, format)
      1 def calculate_q6(timeslice, format="lammps-dump"):
----> 2     sys = timeslice.to_system()[0]
      3     sys.find_neighbors(method="cutoff",cutoff=0)
      4     sys.calculate_q(6)
      5     q6 = sys.get_qvals(6)

~/miniconda3/envs/py37/lib/python3.7/site-packages/pyscal/trajectory.py in to_system(self, customkeys)
     65         for count, traj in enumerate(self.trajectories):
     66             for x in self.blocklists[count]:
---> 67                 s = self.trajectories[count].get_block_as_system(x, customkeys=customkeys)
     68                 sys.append(s)
     69         return sys

~/miniconda3/envs/py37/lib/python3.7/site-packages/pyscal/trajectory.py in get_block_as_system(self, blockno, customkeys)
    372         data = self.get_block(blockno)
    373 
--> 374         sys = pc.System()
    375         sys.read_inputfile(data, customkeys=customkeys)
    376         return sys

NameError: name 'pc' is not defined
```

It seems like the `get_block_as_system` function in the trajectory.py file is trying to call the pyscal package itself?

**Comment by srmnitc** [comment]
@tanooj-s Thanks for the issue. `trajectory` in fact calls the `core` module. This bug was noticed and is now fixed. The fixed version is not yet released however. I will make a release now. If you installed through conda, the new version should be there in couple of hours. If you directly cloned the repo, please update and it should work. I will keep the issue open for your confirmation.

**Comment by tanooj-s** [comment]
It's working now, thanks for the quick response.
